title: "[CI/CD] "
name: "Feature ✨"
description: "Brand new capability or product functionality"
labels: ["area: CI/CD ⚙️"]
body:
  - type: textarea
    id: ci
    attributes:
      label: What part of CI/CD is being worked on?
    validations:
      required: true
