title: "[Cleanup] "
name: "Cleanup 🧽"
description: "Tech debt, code hygiene, dependency pruning"
labels: ["type: cleanup 🧽"]
body:
  - type: textarea
    id: cleanup
    attributes:
      label: What needs to be cleaned up or pruned?
    validations:
      required: true
