title: "[Enhancement] "
name: "Enhancement 🛠️"
description: "Improvements to existing features"
labels: ["type: enhancement 🛠️"]
body:
  - type: textarea
    id: enhancement
    attributes:
      label: What do you want to improve?
    validations:
      required: true
