title: "[Refactor] "
name: "Refactor 🧹"
description: "Code improvements without changing behavior"
labels: ["type: refactor 🧹"]
body:
  - type: textarea
    id: refactor
    attributes:
      label: What code should be cleaned up or restructured?
    validations:
      required: true
