title: "[Research] "
name: "Research 🕵️"
description: "Exploratory task, design or standards investigation"
labels: ["type: research 🕵️"]
body:
  - type: textarea
    id: topic
    attributes:
      label: What are you researching?
    validations:
      required: true
