title: "[Test] "
name: "Test 🧪"
description: "Add or improve automated tests"
labels: ["type: test ✅"]
body:
  - type: textarea
    id: tests
    attributes:
      label: What tests should be added or improved?
    validations:
      required: true
