title: "[UX/UI] "
labels: ["area: UX/UI 💄"]
body:
  - type: textarea
    id: uxui
    attributes:
      label: What part of the interface or user flow is affected?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What improvement do you suggest?
    validations:
      required: false
