name: UX/UI 🎨
description: User experience or interface improvements
title: "[UX/UI] "
labels: ["type: ux/ui 🎨"]
body:
  - type: textarea
    id: uxui
    attributes:
      label: What part of the interface or user flow is affected?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What improvement do you suggest?
    validations:
      required: false
